name: expenses_tracker
description: "An advanced Expense Tracker app with Supabase backend, Charts, and 80% limit notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Backend & Auth
  supabase_flutter: ^2.0.2

  # State Management (Professional choice)
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # UI, Icons & Fonts
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0

  # Advanced UI Elements
  percent_indicator: ^4.2.3 # Budget progress bars ke liye
  skeletonizer: 1.4.2    # Professional loading effect ke liye
  animations: ^2.0.11       # Smooth screen transitions

  # Data Visualization
  fl_chart: ^0.66.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3

  # Image Picking (Nayi cheez jo add ki hai)
  image_picker: ^1.0.7

  # Notifications (Local & Push)
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true